### ISSUE TITLE
dropping Service object causes panic

### ISSUE THREAD

**Issue by lrbalt** [plietar/rust-mdns#7]
If the service object goes out of scope somewhere, running avahi-browse will cause a panic.

If you change the example to drop _svc before the loop:

```rust
extern crate env_logger;
extern crate mdns;
extern crate dns_parser;

pub fn main() {
    env_logger::init().unwrap();

    let responder = {
	let r = mdns::Responder::new().unwrap();
	    let _svc = r.register(
	        "_reinier._tcp".to_owned(),
	        "Web Server".to_owned(),
	        80,
	        &["path=/"]);
	r
    };

    loop {
        ::std::thread::sleep(::std::time::Duration::from_secs(10));
    }
}
```

and run `avahi-browse _reinier._tcp --verbose -r` _after_ starting the example, it will panic:

```
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/register`
thread 'mdns-responder' panicked at 'missing service', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:715
stack backtrace:
   1:     0x56455702581c - std::sys::imp::backtrace::tracing::imp::write::h2a972e172776bc73
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5645570288be - std::panicking::default_hook::{{closure}}::h3350be9abe4c8496
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x5645570284c4 - std::panicking::default_hook::h255964940ef72e84
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x564557028d67 - std::panicking::rust_panic_with_hook::ha02a85ff57cdb669
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x564557028ba4 - std::panicking::begin_panic::h3472a76248a19370
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x564557028b19 - std::panicking::begin_panic_fmt::h353221386e3766a5
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x564557028aa7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x56455704f8cd - core::panicking::panic_fmt::h2a5bed77fd55efc9
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x56455704f93d - core::option::expect_failed::h23107d11ad99421e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:715
  10:     0x564556f43ba3 - <core::option::Option<T>>::expect::h8d3a196141fd9966
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:293
  11:     0x564556fa9494 - <mdns::services::FindByType<'a> as core::iter::iterator::Iterator>::next::{{closure}}::h5bf1d572e2825213
                        at /home/rbalt/Dropbox/src/projects/spherics/rust-mdns/src/services.rs:103
  12:     0x564556f413f5 - <core::option::Option<T>>::map::h0598ca8668bc6e24
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/option.rs:383
  13:     0x564556fa941d - <mdns::services::FindByType<'a> as core::iter::iterator::Iterator>::next::h9468fb169ec4f76c
                        at /home/rbalt/Dropbox/src/projects/spherics/rust-mdns/src/services.rs:99
  14:     0x564556fa4214 - <mdns::fsm::FSM<AF>>::handle_question::h35556df586605e4b
                        at /home/rbalt/Dropbox/src/projects/spherics/rust-mdns/src/fsm.rs:133
  15:     0x564556fa203c - <mdns::fsm::FSM<AF>>::handle_packet::h1fa8c236f223280d
                        at /home/rbalt/Dropbox/src/projects/spherics/rust-mdns/src/fsm.rs:106
  16:     0x564556fa1251 - <mdns::fsm::FSM<AF>>::recv_packets::hf6dc870afc95bc5e
                        at /home/rbalt/Dropbox/src/projects/spherics/rust-mdns/src/fsm.rs:70
  17:     0x564556fa7c1c - <mdns::fsm::FSM<AF> as futures::future::Future>::poll::h9755e7ebe73677c2
                        at /home/rbalt/Dropbox/src/projects/spherics/rust-mdns/src/fsm.rs:270
  18:     0x564556f782df - <futures::future::join::MaybeDone<A>>::poll::hb7c9727508f0f77b
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/future/join.rs:135
  19:     0x564556f9a29e - <futures::future::join::Join<A, B> as futures::future::Future>::poll::h831ed3ef4c898436
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/future/join.rs:50
  20:     0x564556f99d5f - <futures::future::map::Map<A, F> as futures::future::Future>::poll::h372fe9cb72dbce27
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/future/map.rs:29
  21:     0x564556f7d0a0 - <Box<F> as futures::future::Future>::poll::hc804fe87d9aabb51
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/future/mod.rs:101
  22:     0x564556f7d0a0 - <Box<F> as futures::future::Future>::poll::hc804fe87d9aabb51
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/future/mod.rs:101
  23:     0x564556f5411b - <futures::task_impl::Spawn<F>>::poll_future::{{closure}}::h2e23457512cfeada
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:312
  24:     0x564556f5438d - <futures::task_impl::Spawn<T>>::enter::{{closure}}::h04f1d002d1b5242e
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:399
  25:     0x564556f96b7b - futures::task_impl::set::{{closure}}::hf4b954b54f5dd600
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:50
  26:     0x564556f5784d - <std::thread::local::LocalKey<T>>::with::h641d29fd7a07784e
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/local.rs:253
  27:     0x564556f96a69 - futures::task_impl::set::hc267891d4ea78afc
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:47
  28:     0x564556f54287 - <futures::task_impl::Spawn<T>>::enter::h8c9689226f989c83
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:399
  29:     0x564556f540b9 - <futures::task_impl::Spawn<F>>::poll_future::hd55e23456862f417
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.7/src/task_impl/mod.rs:312
  30:     0x564556f3a08e - tokio_core::reactor::Core::run::{{closure}}::hb91e849bff721ac8
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.2/src/reactor/mod.rs:218
  31:     0x564556f4783a - <scoped_tls::ScopedKey<T>>::set::h35300d46ea0b3e16
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  32:     0x564556f39c3f - tokio_core::reactor::Core::run::h9bfa99ea435cdb8b
                        at /home/rbalt/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.2/src/reactor/mod.rs:217
  33:     0x564556faaf47 - mdns::Responder::new::{{closure}}::h3b64ee548e2b2d6f
                        at /home/rbalt/Dropbox/src/projects/spherics/rust-mdns/src/lib.rs:62
  34:     0x564556f9affb - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::hbfbf75dce78cc791
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
  35:     0x564556f510ba - std::panicking::try::do_call::h9acf65bafac63880
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
  36:     0x56455702fd5a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  37:     0x564556f50e31 - std::panicking::try::hb47b67e8e0072bf8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
  38:     0x564556f500ba - std::panic::catch_unwind::hba5333968babd997
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
  39:     0x564556f50ada - std::thread::Builder::spawn::{{closure}}::h25391c655725ebf7
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:302
  40:     0x564556f76e2b - <F as alloc::boxed::FnBox<A>>::call_box::h181151cff6d6cc3c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  41:     0x564557027ba4 - std::sys::imp::thread::Thread::new::thread_start::h27fa49fe81f658e4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  42:     0x7f44657d36c9 - start_thread
  43:     0x7f44652f6f7e - clone
  44:                0x0 - <unknown>
```

**Comment by plietar** [comment]
Thanks for the report, it should work now.
